# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'AdaptyLogger', git: 'https://github.com/adaptyteam/AdaptySDK-iOS.git', branch: 'release/3.15.1'
  pod 'AdaptyUIBuilder', git: 'https://github.com/adaptyteam/AdaptySDK-iOS.git', branch: 'release/3.15.1'
  pod 'Adapty', git: 'https://github.com/adaptyteam/AdaptySDK-iOS.git', branch: 'release/3.15.1'
  pod 'AdaptyUI', git: 'https://github.com/adaptyteam/AdaptySDK-iOS.git', branch: 'release/3.15.1'
  pod 'AdaptyPlugin', git: 'https://github.com/adaptyteam/AdaptySDK-iOS.git', branch: 'release/3.15.1'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -DDISABLE_TRUEDEPTH_API'
    end
  end
end
